### PR TITLE
Support for Swiss  cantons.

### PR DESCRIPTION
**Pull request by sergedroz**
I've added support for swiss cantons, analogous to the French departments. As identifiers/key's I've used the expression kt-xx, where xx ist the short for the respective canton.

### CODE REVIEW

**Comment by paradoxxxzero** [comment]
Nice work, thanks !

**Comment by paradoxxxzero** [comment]
I fixed some bugs, please remember to run the tests before submitting PR. Anyway thanks for the PR.

**Comment by sergedroz** [comment]
Hi Florian

sorry for the test. I'll do that next time.
Quick question: Did you forget to add the maps (.sgv) to git?


>>>> import pygal
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "pygal/__init__.py", line 29, in <module>
>     from pygal.graph.frenchmap import FrenchMapDepartments, FrenchMapRegions
>   File "pygal/graph/frenchmap.py", line 173, in <module>
>     'fr.departments.svg')) as file:
> IOError: [Errno 2] No such file or directory: 'pygal/graph/maps/fr.departments.svg'

Cheers
Serge

**Comment by paradoxxxzero** [comment]
Whoops I have moved them in a subdirectory and have been tricked once again
by the gitignore.. This should be fixed now.

**Pull request merged**
